version: '3'
services:
# docker run --name elan.dev -itd \
#  --privileged --cap-add=SYS_PTRACE 
#  --security-opt seccomp=unconfined 
#  --network host \
#  -w ${HOME}/workspace \
#  -v ${HOME}/workspace:${HOME}/workspace \
#  -v ${HOME}/.gitconfig:/root/.gitconfig \
#  -v ${HOME}/.bash_history:/root/.bash_history \
#  -v ${HOME}/Downloads:/root/Downloads elan.dev bash
  elan.dev:
    build:
      context: .
      dockerfile: Dockerfile.elan.dev
    container_name: elan.dev
    cap_add:
      - ALL
    privileged: true
    security_opt:
      - seccomp:unconfined
    network_mode: host
    working_dir: ${HOME}/workspace
    volumes:
      - ${HOME}/workspace:${HOME}/workspace
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.bash_history:/root/.bash_history
      - ${HOME}/Downloads:/root/Downloads
    tty: true
    command: bash
    restart: always
